Repository Ralim/IronOS, pull requests merged in 2024-11, with the labels that each got.

#1991 README update
  README.md
Labels: Documentation

#1996 README.md: fix mistypes discovered by @yo3fxy
  README.md
Labels: Documentation

#1998 Added translation into Uzbek
  Translations/translation_UZ.json
Labels: Awaiting Response, Translations

#1999 Check the presence of changelog for the latest stable release in History.md
  .github/workflows/push.yml
  Documentation/History.md
  Makefile
  scripts/deploy.sh
Labels: Build System, Documentation

#2005 source/Makefile: enable builds for supported but missing languages
  source/Makefile
Labels: Translations, Build System

#2006 Langs check
  scripts/deploy.sh
Labels: Translations, Build System

#2007 Add Belorussian language as part of Cyrillic multilang builds
  .github/workflows/push.yml
  Documentation/Development.md
  Makefile
  source/Makefile
Labels: Translations, Build System, Documentation
