Repository Ralim/IronOS, pull requests merged in 2025-02, with the labels that each got.

#2064 scripts/deploy.sh: add handmade linter for translation-related json files to check for tabs and odd spaces
  .github/workflows/push.yml
  Makefile
  Translations/translation_UZ.json
  scripts/deploy.sh
Labels: Translations, Build System

#2065 refactor(core/settingsgui): code cleaning
  source/Core/Src/settingsGUI.cpp
Labels: Refactoring

#2067 README.md: add notice about BLE turned off by default now
  README.md
Labels: Documentation

#2068 README.md: fix formatting of heading levels for BLE section
  README.md
Labels: Documentation

#2060 Added guide for compiling under Windows
  Documentation/Development.md
  source/Core/BSP/MHP30/BSP.cpp
  source/Core/BSP/MHP30/ThermoModel.cpp
  source/Core/BSP/Miniware/ThermoModel.cpp
  source/Core/BSP/Pinecil/ThermoModel.cpp
  source/Core/BSP/Pinecilv2/BSP.cpp
  source/Core/BSP/Pinecilv2/ThermoModel.cpp
  source/Core/BSP/Pinecilv2/bl_mcu_sdk/components/ble/ble_stack/port/include/bl_port.h
  source/Core/BSP/Pinecilv2/ble_peripheral.h
  source/Core/BSP/Sequre/ThermoModel.cpp
  source/Core/Drivers/HUB238.cpp
  source/Core/Drivers/TipThermoModel.cpp
  source/Core/Drivers/Utils.cpp
  source/Core/Drivers/Utils.hpp
  source/Core/Inc/Types.h
  source/Makefile
Labels: Documentation

#2074 Add the notice about EPR/PPS disabled by default in the main README.md
  README.md
Labels: Documentation

#2075 Debug Menu: add time of compilation to timestamp build
  Documentation/DebugMenu.md
  Translations/make_translation.py
Labels: Build System, Documentation
