Repository Ralim/IronOS, pull requests merged in 2025-03, with the labels that each got.

#2084 Add notice in README about another revision of TS101 with a different not supported yet OLED model
  README.md
Labels: Documentation

#2059 Add option to swap A / B buttons in Settings menu
  Translations/translation_BE.json
  Translations/translation_BG.json
  Translations/translation_CS.json
  Translations/translation_DA.json
  Translations/translation_DE.json
  Translations/translation_EL.json
  Translations/translation_EN.json
  Translations/translation_ES.json
  Translations/translation_ET.json
  Translations/translation_FI.json
  Translations/translation_FR.json
  Translations/translation_HR.json
  Translations/translation_HU.json
  Translations/translation_IT.json
  Translations/translation_JA_JP.json
  Translations/translation_LT.json
  Translations/translation_NB.json
  Translations/translation_NL.json
  Translations/translation_NL_BE.json
  Translations/translation_PL.json
  Translations/translation_PT.json
  Translations/translation_RO.json
  Translations/translation_RU.json
  Translations/translation_SK.json
  Translations/translation_SL.json
  Translations/translation_SR_CYRL.json
  Translations/translation_SR_LATN.json
  Translations/translation_SV.json
  Translations/translation_TR.json
  Translations/translation_UK.json
  Translations/translation_UZ.json
  Translations/translation_VI.json
  Translations/translation_YUE_HK.json
  Translations/translation_ZH_CN.json
  Translations/translation_ZH_TW.json
  Translations/translations_definitions.json
  patches/README.md
  patches/swap-buttons-fully.diff
  source/Core/BSP/MHP30/configuration.h
  source/Core/BSP/Miniware/configuration.h
  source/Core/BSP/Pinecil/configuration.h
  source/Core/BSP/Pinecilv2/configuration.h
  source/Core/BSP/Sequre/configuration.h
  source/Core/Drivers/Buttons.cpp
  source/Core/Drivers/Buttons.hpp
  source/Core/Inc/Settings.h
  source/Core/Inc/Translation.h
  source/Core/Src/Settings.cpp
  source/Core/Src/settingsGUI.cpp
  source/Core/Threads/GUIThread.cpp
  source/Core/Threads/UI/drawing/mono_128x32/draw_homescreen_simplified.cpp
  source/Core/Threads/UI/drawing/mono_96x16/draw_homescreen_simplified.cpp
  source/Core/Threads/UI/logic/TemperatureAdjust.cpp
Labels: Usability

#2097 push.yml: update runs-on to ubuntu-24.04 to fix upload_metadata build step
  .github/workflows/push.yml
Labels: Bug, Build System

#2098 Revert "Add option to swap A / B buttons in Settings menu"
  Translations/translation_BE.json
  Translations/translation_BG.json
  Translations/translation_CS.json
  Translations/translation_DA.json
  Translations/translation_DE.json
  Translations/translation_EL.json
  Translations/translation_EN.json
  Translations/translation_ES.json
  Translations/translation_ET.json
  Translations/translation_FI.json
  Translations/translation_FR.json
  Translations/translation_HR.json
  Translations/translation_HU.json
  Translations/translation_IT.json
  Translations/translation_JA_JP.json
  Translations/translation_LT.json
  Translations/translation_NB.json
  Translations/translation_NL.json
  Translations/translation_NL_BE.json
  Translations/translation_PL.json
  Translations/translation_PT.json
  Translations/translation_RO.json
  Translations/translation_RU.json
  Translations/translation_SK.json
  Translations/translation_SL.json
  Translations/translation_SR_CYRL.json
  Translations/translation_SR_LATN.json
  Translations/translation_SV.json
  Translations/translation_TR.json
  Translations/translation_UK.json
  Translations/translation_UZ.json
  Translations/translation_VI.json
  Translations/translation_YUE_HK.json
  Translations/translation_ZH_CN.json
  Translations/translation_ZH_TW.json
  Translations/translations_definitions.json
  patches/README.md
  patches/swap-buttons-fully.diff
  source/Core/BSP/MHP30/configuration.h
  source/Core/BSP/Miniware/configuration.h
  source/Core/BSP/Pinecil/configuration.h
  source/Core/BSP/Pinecilv2/configuration.h
  source/Core/BSP/Sequre/configuration.h
  source/Core/Drivers/Buttons.cpp
  source/Core/Drivers/Buttons.hpp
  source/Core/Inc/Settings.h
  source/Core/Inc/Translation.h
  source/Core/Src/Settings.cpp
  source/Core/Src/settingsGUI.cpp
  source/Core/Threads/GUIThread.cpp
  source/Core/Threads/UI/drawing/mono_128x32/draw_homescreen_simplified.cpp
  source/Core/Threads/UI/drawing/mono_96x16/draw_homescreen_simplified.cpp
  source/Core/Threads/UI/logic/TemperatureAdjust.cpp
Labels: Bug

#2099 Adding Pinecilv2 ws2812b mod option
  Documentation/README.md
  Documentation/WS2812BModding.md
  scripts/IronOS-mkdocs.yml
  source/Core/BSP/Pinecilv2/BSP.cpp
  source/Core/BSP/Pinecilv2/Pins.h
  source/Core/BSP/Pinecilv2/preRTOS.cpp
  source/Core/Drivers/WS2812B.h
  source/Makefile
  source/build.sh
Labels: Enhancement, Documentation

#2102 Disable animation between home and soldering screens if detailed view is set for both modes (probably a finally proper fix for #2076)
  source/Core/Threads/GUIThread.cpp
  source/Core/Threads/UI/logic/HomeScreen.cpp
  source/Core/Threads/UI/logic/Soldering.cpp
Labels: Bug, Usability

#2107 Update debug time stamp according to the official recommendation from reproducible builds initiative by @paulfertser suggestion
  Translations/make_translation.py
Labels: Build System

#2108 Makefile: add diff output for python linter if there are some warnings
  .github/workflows/push.yml
  Makefile
Labels: Build System

#2103 Add option to swap A/B buttons in Settings menu with minimal changes (fix for #2034)
  Translations/translation_BE.json
  Translations/translation_BG.json
  Translations/translation_CS.json
  Translations/translation_DA.json
  Translations/translation_DE.json
  Translations/translation_EL.json
  Translations/translation_EN.json
  Translations/translation_ES.json
  Translations/translation_ET.json
  Translations/translation_FI.json
  Translations/translation_FR.json
  Translations/translation_HR.json
  Translations/translation_HU.json
  Translations/translation_IT.json
  Translations/translation_JA_JP.json
  Translations/translation_LT.json
  Translations/translation_NB.json
  Translations/translation_NL.json
  Translations/translation_NL_BE.json
  Translations/translation_PL.json
  Translations/translation_PT.json
  Translations/translation_RO.json
  Translations/translation_RU.json
  Translations/translation_SK.json
  Translations/translation_SL.json
  Translations/translation_SR_CYRL.json
  Translations/translation_SR_LATN.json
  Translations/translation_SV.json
  Translations/translation_TR.json
  Translations/translation_UK.json
  Translations/translation_UZ.json
  Translations/translation_VI.json
  Translations/translation_YUE_HK.json
  Translations/translation_ZH_CN.json
  Translations/translation_ZH_TW.json
  Translations/translations_definitions.json
  source/Core/Inc/Settings.h
  source/Core/Inc/Translation.h
  source/Core/Src/Settings.cpp
  source/Core/Src/settingsGUI.cpp
  source/Core/Threads/UI/logic/DebugMenu.cpp
  source/Core/Threads/UI/logic/HomeScreen.cpp
  source/Core/Threads/UI/logic/SettingsMenu.cpp
Labels: Enhancement, Usability
